history search

diff --git a/bin/set-dns b/bin/set-dns
--- a/bin/set-dns
+++ b/bin/set-dns
@@ -1,14 +1,32 @@
 #!/usr/bin/env bash
 
-readarray -t CONNECTIONS <<< $(nmcli -t -f NAME connection)
-for CONNECTION in "${CONNECTIONS[@]}"; do
-  TYPE=$(nmcli connection show "$CONNECTION" | grep connection.type: | tr -s " " | cut -d " " -f2-)
-  echo $CONNECTION
-  if grep -E -i "(wireless|ethernet)" <<< "$TYPE" &>/dev/null; then
-    nmcli connection modify "$CONNECTION" \
-      ipv4.dns "8.8.8.8 8.8.4.4" \
-      ipv6.dns "2001:4860:4860::8888 2001:4860:4860::8844" \
-      # ipv4.ignore-auto-dns "yes" \
-      # ipv6.ignore-auto-dns "yes"
-  fi
+while getopts "d" o &>/dev/null; do
+  case $o in
+    "d") DELETE=true ;;
+  esac
 done
+
+shift "$(($OPTIND - 1))"
+CONNECTION=${1}
+
+if [[ -z $CONNECTION ]]; then
+  echo "connection argument is missing"
+  exit 1
+fi
+
+# readarray -t CONNECTIONS <<< $(nmcli -t -f NAME connection)
+# for CONNECTION in "${CONNECTIONS[@]}"; do
+# TYPE=$(nmcli connection show "$CONNECTION" | grep connection.type: | tr -s " " | cut -d " " -f2-)
+# echo $CONNECTION
+# if grep -E -i "(wireless|ethernet)" <<< "$TYPE" &>/dev/null; then
+if [[ -z $DELETE ]]; then
+  nmcli connection modify "$CONNECTION" \
+    ipv4.dns "8.8.8.8 8.8.4.4" \
+    ipv6.dns "2001:4860:4860::8888 2001:4860:4860::8844"
+else
+  nmcli connection modify "$CONNECTION" ipv4.dns "" ipv6.dns ""
+fi
+# ipv4.ignore-auto-dns "yes" \
+# ipv6.ignore-auto-dns "yes"
+# fi
+# done
